INSERT INTO MEMBER ( MEMBER_ID, USERNAME, PASSWORD, EMAIL, ACTIVATED)
VALUES (1,'admin','$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi','wj100213@gmail.com',1);

INSERT INTO MEMBER ( MEMBER_ID, USERNAME, PASSWORD, EMAIL, ACTIVATED)
VALUES (2,'user1','$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi','lokshopi2@naver.com',1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO member_authority (MEMBER_ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO member_authority (MEMBER_ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO member_authority (MEMBER_ID, AUTHORITY_NAME) values (2, 'ROLE_USER');